# Site settings
author: Kyle Brett Beckstead
title: Kyle Beckstead
header-img: img/home-bg.png
email: kyle21beckstead@gmail.com
copyright_name: Kyle Brett Beckstead
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Kylebrettb

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
